### ISSUE TITLE
Deze functie in manager is grotendeels een data-layer functie

### ISSUE THREAD

**Issue by JeroenHeemskerk** [MaikelSchuurmans/educom-java-MI6#7]
https://github.com/MaikelSchuurmans/educom-java-MI6/blob/81e1e2a017b06890013bdcd5cac972a3c158ff76/src/main/java/nu/educom/MI6/data/AgentManager.java#L27-L46

Deze code bevat zowel code om in de database de Agent te maken, als hem te valideren, misschien moet je onder AgentManager ook een AgentCrud of AgentReprository neerleggen en dan regel 28-39 in een `readAgent(int serviceNumber)` zetten en daar ook functies als `createLoginAttempt(LoginAttempt attempt)` en `readLastFailedLoginAttempts(Agent agent)` ofzo

**Comment by MaikelSchuurmans** [comment]
Dit had ik gedaan aangezien dit een eis was in issue #5 
Maar zal het aanpassen
